### ISSUE TITLE
Duplicate, unnecessary, file.

### ISSUE THREAD

**Issue by JimCownie** [parallel-runtimes/lomp#10]
**Describe the bug**
The file `stats-timing.cc` is present in both the microBM and src directories. The one in microBM is old and unused, so should be removed.

**To Reproduce**
Please provide steps to reproduce the behavior:
1. cd top-level-dir
2. $ find . -name stats-timing.cc
    ./microBM/stats-timing.cc
    ./src/stats-timing.cc

3. Observe the two files, then check the CMakeLists.txt in microBM to verify that all of the executables are built with 
`add_executable(yield yield.cc ../src/stats-timing.cc ../src/util.cc)` which references the file in ../src, not the local one.

**Expected behavior**
There should only be the source file which is needed, not the old, confusing, one in microBM

**Desktop (please complete the following information):**
- OS: All
- Target architecture: All
-  LOMP Version: Current

**Comment by mjklemm** [comment]
This has been merged a good while ago.
