### ISSUE TITLE
LOMP does not Build on 32-bit Arm

### ISSUE THREAD

**Issue by mjklemm** [parallel-runtimes/lomp#33]
**Describe the bug**
There is a compilation issue in the 32-bit Arm code:

> In file included from /net/home/micha/projects/lomp/sources/src/stats-timing.cc:20:
> /net/home/micha/projects/lomp/sources/./src/target.h:140:2: warning: "The FlushAddress() function is a no-op on this architecture" [-W#warnings]
> #warning "The FlushAddress() function is a no-op on this architecture"
>  ^
> /net/home/micha/projects/lomp/sources/src/stats-timing.cc:145:21: error: use of undeclared identifier 'getArmID'
>   uint32_t el1Reg = getArmID();
>                     ^
> 1 warning and 1 error generated.
> ninja: build stopped: subcommand failed.
> 

**To Reproduce**
Please provide steps to reproduce the behavior:
1. Checkout `main` branch
2. Compile on Arm 32-bit

**Expected behavior**
No compiler error.

**Screenshots**
See error message above.

**Desktop (please complete the following information):**
- OS: Linux
- Target architecture: armv7l
-  LOMP Version: f9a18972

**Comment by mjklemm** [comment]
The same happens on my RISC-V:

```
[1/36] Building CXX object src/CMakeFiles/omp.dir/stats-timing.cc.o
FAILED: src/CMakeFiles/omp.dir/stats-timing.cc.o
/usr/bin/clang++ -DDEBUG=10 -DLOMP_BUILD_RTL=1 -DLOMP_HAVE_LIBATOMIC=1 -DLOMP_HAVE_LIBNUMA=1 -DLOMP_WARN_API_STUBS=1 -DLOMP_WARN_ARCH_FEATURES=1 -Domp_EXPORTS -I/net/home/micha/projects/lomp/sources/./include -I/net/home/micha/projects/lomp/sources/./src -Isrc -fPIC -std=c++17 -MD -MT src/CMakeFiles/omp.dir/stats-timing.cc.o -MF src/CMakeFiles/omp.dir/stats-timing.cc.o.d -o src/CMakeFiles/omp.dir/stats-timing.cc.o -c /net/home/micha/projects/lomp/sources/src/stats-timing.cc
In file included from /net/home/micha/projects/lomp/sources/src/stats-timing.cc:20:
/net/home/micha/projects/lomp/sources/./src/target.h:140:2: warning: "The FlushAddress() function is a no-op on this architecture" [-W#warnings]
#warning "The FlushAddress() function is a no-op on this architecture"
 ^
/net/home/micha/projects/lomp/sources/src/stats-timing.cc:145:21: error: use of undeclared identifier 'getArmID'
  uint32_t el1Reg = getArmID();
                    ^
1 warning and 1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by JimCownie** [comment]
Try the gcc branch. I believe I fixed this there.

-- Jim
+44 780 637 7146

**Comment by mjklemm** [comment]
I have cherrypicked commit b8d2bc23d408d10de86002be840eaac76f798058 and it seems to fix the compilation issue.

**Comment by JimCownie** [comment]
Great, thanks!

-- Jim
+44 780 637 7146

**Comment by mjklemm** [comment]
This one has been fixed.
